version: "3"

services:
  track-metadata:
    build: .
    ports:
    - 8080:8080
    - 5005:5005
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/track_metadata
      KUMULUZEE_DATASOURCES0_USERNAME: dbuser
      KUMULUZEE_DATASOURCES0_PASSWORD: postgres
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=track-metadata:5005
    depends_on:
    - postgres
    - etcd

  postgres:
    image: postgres:10.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: track_metadata

  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
      - 2379:2379
    command: >-
      /usr/local/bin/etcd
      -name node1
      -advertise-client-urls http://etcd:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster node1=http://etcd:2380
      -cors="*"

  etcd-browser:
    image: buddho/etcd-browser
    ports:
    - 8082:8080
    environment:
      ETCD_HOST: etcd
      ETCD_PORT: 2379
      SERVER_PORT: 8080
    depends_on:
    - etcd