kumuluzee:
  name: rso-trackData
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/TrackDataDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/track_data
      username: postgres
      password:
      max-pool-size: 20
rest-properties:
  external-services:
    order-service:
      enabled: true
