kumuluzee:
  name: rso-track-data
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/TrackDataDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/track_data
#      localhost or 192.168.99.100
      username: dbuser
      password: postgres
      max-pool-size: 20

  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/TrackDataDS
      etcd-health-check:
        connection-url: http://etcd:2379/health
  config:
    etcd:
      hosts: http://159.122.187.192:30774
  discovery:
    etcd:
      hosts: http://159.122.187.192:30774

app-properties:
  api:
    filtering:
      enabled: true
  endpoint:
    zc: http://localhost:8090/v1/track-data
    mm: http://localhost:8091/v1/track-metadata




